jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use GitHub Token
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Using token for authentication"
